name: "AWS Terraform Deploy"

on:
  workflow_dispatch:
    # 💡 ココ！実行するときに「構築」か「解体」を画面で選べるようにします
    inputs:
      action:
        description: '実行するアクションを選択してください'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sigv4
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::058264368153:role/GitHubActionsWorkflowRole

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      # 💡 画面で選んだアクション（apply または destroy）がここに自動で入ります
      - name: Terraform Run
        run: terraform ${{ github.event.inputs.action }} -auto-approve
